### ISSUE TITLE
Layer React Native

### ISSUE THREAD

**Issue by dabit3** [layerhq/layer-react#6]
Any plans on a React Native implementation?

**Comment by blackxored** [comment]
In my findings it's not this library but layer-websdk who needs considerable fixes to make it work on RN. I've a working fork, but far from ready for outside-my-own-project testing :P Will get back to them after I release my app.

**Comment by dabit3** [comment]
@blackxored Thanks for the update :)

**Comment by blackxored** [comment]
Please track on layer-webksdk#85.
